"""Remove test fields - complete migration test

Revision ID: c4bff4478223
Revises: 9cb2ed91a331
Create Date: 2025-05-26 11:50:36.717524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bff4478223'
down_revision = '9cb2ed91a331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('migration_test_complete')
        batch_op.drop_column('test_migration_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_migration_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('migration_test_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
